const SERVER_BASEURL_SERVICES = process.env.SERVER_BASEURL_SERVICES;
const BUCKET_UPLOAD_BASEURL = process.env.REACT_APP_BUCKET_UPLOAD_BASEURL;
export { SERVER_BASEURL_SERVICES,BUCKET_UPLOAD_BASEURL }